const Data = [
  {
    full_name: "Kellsie Deackes",
    employee_id: "E6273",
    date_of_birth: "84/16/1727",
    email: "jmaior0@shareasale.com",
    gender: "Female",
    marital_status: "married",
    blood_group: "AB-",
    phone_number: "2509558382",
    address: "Suite 21",
    job_title: "AI",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "Hyderabad",
    supervisor: "Goldarina Mourge",
    emergency_contact_name: "Jessica Maior",
    emergency_relation: "brother",
    emergency_phone_number: "5471676104",
    laptop_name: "Apple MacBook Pro",
    laptop_serial_no: "L72068BE87",
    employee_email: "jmaior0@admin.ch",
  },
  {
    full_name: "Carmina Legg",
    employee_id: "E0603",
    date_of_birth: "90/55/2189",
    email: "apirnie1@lulu.com",
    gender: "Female",
    marital_status: "married",
    blood_group: "O-",
    phone_number: "6089817932",
    address: "Room 1658",
    job_title: "Testing",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "Ts",
    supervisor: "Wandie Oakden",
    emergency_contact_name: "Ashley Pirnie",
    emergency_relation: "brother",
    emergency_phone_number: "9571806242",
    laptop_name: "Lenovo ThinkPad",
    laptop_serial_no: "94Q7OY1504",
    employee_email: "apirnie1@cloudflare.com",
  },
  {
    full_name: "Sheridan Crosscombe",
    employee_id: "E7036",
    date_of_birth: "04/65/3906",
    email: "eheibl2@aol.com",
    gender: "Male",
    marital_status: "married",
    blood_group: "A+",
    phone_number: "1455308799",
    address: "Apt 1007",
    job_title: "Testing",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "Hyderabad",
    supervisor: "Dimitri Troy",
    emergency_contact_name: "Esra Heibl",
    emergency_relation: "brother",
    emergency_phone_number: "6652579506",
    laptop_name: "Razer Blade",
    laptop_serial_no: "DGYZ4L6502",
    employee_email: "eheibl2@hugedomains.com",
  },
  {
    full_name: "Hershel Halle",
    employee_id: "E4261",
    date_of_birth: "85/28/9126",
    email: "lkrzyzanowski3@reference.com",
    gender: "Male",
    marital_status: "single",
    blood_group: "B-",
    phone_number: "2570506697",
    address: "Room 186",
    job_title: "AI",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "Hyderabad",
    supervisor: "Adham Tireman",
    emergency_contact_name: "Leroi Krzyzanowski",
    emergency_relation: "mother",
    emergency_phone_number: "2305269045",
    laptop_name: "HP Spectre",
    laptop_serial_no: "3T6U4073A3",
    employee_email: "lkrzyzanowski3@nymag.com",
  },
  {
    full_name: "Paige Lerohan",
    employee_id: "E2504",
    date_of_birth: "49/32/9354",
    email: "mheinz4@blogspot.com",
    gender: "Female",
    marital_status: "married",
    blood_group: "O-",
    phone_number: "8766545026",
    address: "PO Box 76242",
    job_title: "Testing",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "Hyderabad",
    supervisor: "Mead Woodhouse",
    emergency_contact_name: "Merrill Heinz",
    emergency_relation: "brother",
    emergency_phone_number: "4072771219",
    laptop_name: "Razer Blade",
    laptop_serial_no: "09007X5R0Z",
    employee_email: "mheinz4@hugedomains.com",
  },
  {
    full_name: "Kleon Sokill",
    employee_id: "E3165",
    date_of_birth: "59/22/6583",
    email: "kdugall5@ucsd.edu",
    gender: "Male",
    marital_status: "married",
    blood_group: "B-",
    phone_number: "2157233517",
    address: "PO Box 80749",
    job_title: "Full stack Developer",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "Ts",
    supervisor: "Chick Dmitrichenko",
    emergency_contact_name: "Kele Dugall",
    emergency_relation: "mother",
    emergency_phone_number: "5788520417",
    laptop_name: "Apple MacBook Pro",
    laptop_serial_no: "2214L63K22",
    employee_email: "kdugall5@icio.us",
  },
  {
    full_name: "Hyacintha Ilyasov",
    employee_id: "E5281",
    date_of_birth: "09/50/6451",
    email: "bschruyers6@mapy.cz",
    gender: "Female",
    marital_status: "married",
    blood_group: "AB-",
    phone_number: "5685357665",
    address: "7th Floor",
    job_title: "Data_analyst",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "India",
    supervisor: "Maire Wawer",
    emergency_contact_name: "Bobbi Schruyers",
    emergency_relation: "brother",
    emergency_phone_number: "7335583981",
    laptop_name: "Alienware Area-51",
    laptop_serial_no: "U143IWD983",
    employee_email: "bschruyers6@bandcamp.com",
  },
  {
    full_name: "Katee Bickerstaff",
    employee_id: "E6973",
    date_of_birth: "46/77/5819",
    email: "syates7@ebay.com",
    gender: "Female",
    marital_status: "single",
    blood_group: "B+",
    phone_number: "1374439055",
    address: "PO Box 80952",
    job_title: "AI",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "Hyderabad",
    supervisor: "Didi Skudder",
    emergency_contact_name: "Selena Yates",
    emergency_relation: "father",
    emergency_phone_number: "7351757273",
    laptop_name: "Alienware Area-51",
    laptop_serial_no: "XV3XYNHN36",
    employee_email: "syates7@jugem.jp",
  },
  {
    full_name: "Charita Marchiso",
    employee_id: "E6763",
    date_of_birth: "21/75/1643",
    email: "kfevers8@nifty.com",
    gender: "Female",
    marital_status: "single",
    blood_group: "A-",
    phone_number: "4482515142",
    address: "Room 1285",
    job_title: "Full stack Developer",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "Hyderabad",
    supervisor: "Donni Cookley",
    emergency_contact_name: "Kathe Fevers",
    emergency_relation: "son",
    emergency_phone_number: "1023660592",
    laptop_name: "Acer Swift",
    laptop_serial_no: "PY18BNX2FZ",
    employee_email: "kfevers8@eventbrite.com",
  },
  {
    full_name: "Zebulon Golley",
    employee_id: "E0669",
    date_of_birth: "24/29/6164",
    email: "ddiprose9@ovh.net",
    gender: "Male",
    marital_status: "single",
    blood_group: "AB-",
    phone_number: "9365293931",
    address: "Apt 1045",
    job_title: "AI",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "Ts",
    supervisor: "Haskel Hayne",
    emergency_contact_name: "Denys Diprose",
    emergency_relation: "brother",
    emergency_phone_number: "3082840718",
    laptop_name: "Apple MacBook Pro",
    laptop_serial_no: "FUIO7E10PX",
    employee_email: "ddiprose9@deliciousdays.com",
  },
  {
    full_name: "Harman Scrauniage",
    employee_id: "E6289",
    date_of_birth: "62/03/9366",
    email: "tbreewooda@microsoft.com",
    gender: "Male",
    marital_status: "married",
    blood_group: "AB-",
    phone_number: "3144116971",
    address: "Suite 32",
    job_title: "Full stack Developer",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "Ts",
    supervisor: "Abeu Rearden",
    emergency_contact_name: "Thoma Breewood",
    emergency_relation: "father",
    emergency_phone_number: "8171718900",
    laptop_name: "Microsoft Surface",
    laptop_serial_no: "4Q4X2CRL01",
    employee_email: "tbreewooda@ted.com",
  },
  {
    full_name: "Janifer Chomicki",
    employee_id: "E4092",
    date_of_birth: "48/46/7612",
    email: "ckleintb@bandcamp.com",
    gender: "Female",
    marital_status: "married",
    blood_group: "A+",
    phone_number: "9391701580",
    address: "13th Floor",
    job_title: "Testing",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "Ts",
    supervisor: "Benoite Ondrus",
    emergency_contact_name: "Christian Kleint",
    emergency_relation: "father",
    emergency_phone_number: "8882287501",
    laptop_name: "Dell XPS",
    laptop_serial_no: "64HJ9A0F61",
    employee_email: "ckleintb@hc360.com",
  },
  {
    full_name: "Ernest Howford",
    employee_id: "E6954",
    date_of_birth: "09/93/2689",
    email: "skinzelc@google.com.br",
    gender: "Male",
    marital_status: "married",
    blood_group: "O-",
    phone_number: "9057550723",
    address: "Apt 980",
    job_title: "Testing",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "Hyderabad",
    supervisor: "Sasha Hector",
    emergency_contact_name: "Salem Kinzel",
    emergency_relation: "son",
    emergency_phone_number: "7130028313",
    laptop_name: "Dell XPS",
    laptop_serial_no: "7GXU5B6IZH",
    employee_email: "skinzelc@drupal.org",
  },
  {
    full_name: "Rita Litel",
    employee_id: "E7803",
    date_of_birth: "34/56/4200",
    email: "dbycraftd@comsenz.com",
    gender: "Female",
    marital_status: "single",
    blood_group: "B+",
    phone_number: "1949039633",
    address: "PO Box 87833",
    job_title: "Data_analyst",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "Hyderabad",
    supervisor: "Morganica Fairtlough",
    emergency_contact_name: "Delly Bycraft",
    emergency_relation: "mother",
    emergency_phone_number: "3614354031",
    laptop_name: "Lenovo ThinkPad",
    laptop_serial_no: "M198TLPH77",
    employee_email: "dbycraftd@whitehouse.gov",
  },
  {
    full_name: "Caroline Bradder",
    employee_id: "E5266",
    date_of_birth: "59/20/4523",
    email: "asheringhame@nba.com",
    gender: "Female",
    marital_status: "married",
    blood_group: "A+",
    phone_number: "1035493871",
    address: "1st Floor",
    job_title: "Full stack Developer",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "Hyderabad",
    supervisor: "Annnora Bestwick",
    emergency_contact_name: "Arluene Sheringham",
    emergency_relation: "mother",
    emergency_phone_number: "0416390367",
    laptop_name: "Apple MacBook Pro",
    laptop_serial_no: "9OIY52IARH",
    employee_email: "asheringhame@artisteer.com",
  },
  {
    full_name: "Charmion Turneux",
    employee_id: "E1774",
    date_of_birth: "55/49/4048",
    email: "dmackettrickf@ebay.com",
    gender: "Female",
    marital_status: "single",
    blood_group: "A+",
    phone_number: "1001585507",
    address: "PO Box 34150",
    job_title: "AI",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "Ts",
    supervisor: "Elene Willox",
    emergency_contact_name: "Danila MacKettrick",
    emergency_relation: "son",
    emergency_phone_number: "5007002984",
    laptop_name: "Microsoft Surface",
    laptop_serial_no: "XACR5TVL07",
    employee_email: "dmackettrickf@intel.com",
  },
  {
    full_name: "Tedman Loverock",
    employee_id: "E5460",
    date_of_birth: "24/16/5773",
    email: "rsendleyg@aboutads.info",
    gender: "Male",
    marital_status: "married",
    blood_group: "B-",
    phone_number: "5835293384",
    address: "PO Box 74638",
    job_title: "Full stack Developer",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "Hyderabad",
    supervisor: "Spike Cisec",
    emergency_contact_name: "Rriocard Sendley",
    emergency_relation: "brother",
    emergency_phone_number: "3520279452",
    laptop_name: "Asus ZenBook",
    laptop_serial_no: "9Z00894829",
    employee_email: "rsendleyg@tuttocitta.it",
  },
  {
    full_name: "Tamra Keoghan",
    employee_id: "E9542",
    date_of_birth: "33/29/6782",
    email: "mmacgraithh@ftc.gov",
    gender: "Female",
    marital_status: "married",
    blood_group: "AB+",
    phone_number: "3106650945",
    address: "Suite 40",
    job_title: "AI",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "India",
    supervisor: "Mariam Dundridge",
    emergency_contact_name: "Maire MacGraith",
    emergency_relation: "father",
    emergency_phone_number: "6274965880",
    laptop_name: "Razer Blade",
    laptop_serial_no: "063H08TPG1",
    employee_email: "mmacgraithh@ameblo.jp",
  },
  {
    full_name: "Kordula Hulle",
    employee_id: "E9443",
    date_of_birth: "05/33/6937",
    email: "drusbridgei@cdbaby.com",
    gender: "Female",
    marital_status: "single",
    blood_group: "A+",
    phone_number: "4034465017",
    address: "Apt 550",
    job_title: "Testing",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "India",
    supervisor: "Caroline Forkan",
    emergency_contact_name: "Daron Rusbridge",
    emergency_relation: "brother",
    emergency_phone_number: "2498975758",
    laptop_name: "Microsoft Surface",
    laptop_serial_no: "JVOP1722F0",
    employee_email: "drusbridgei@mtv.com",
  },
  {
    full_name: "Giovanna Try",
    employee_id: "E8154",
    date_of_birth: "14/58/6590",
    email: "djimsonj@illinois.edu",
    gender: "Female",
    marital_status: "married",
    blood_group: "A-",
    phone_number: "5923418191",
    address: "PO Box 81727",
    job_title: "Full stack Developer",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "Hyderabad",
    supervisor: "Caprice Palmar",
    emergency_contact_name: "Danella Jimson",
    emergency_relation: "mother",
    emergency_phone_number: "8328110443",
    laptop_name: "Asus ZenBook",
    laptop_serial_no: "C87I49VEY4",
    employee_email: "djimsonj@4shared.com",
  },
  {
    full_name: "Oliver Worsnup",
    employee_id: "E2206",
    date_of_birth: "69/07/8016",
    email: "wdeveyk@wufoo.com",
    gender: "Male",
    marital_status: "married",
    blood_group: "AB+",
    phone_number: "6164374427",
    address: "Suite 63",
    job_title: "Testing",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "India",
    supervisor: "Wilburt Jiran",
    emergency_contact_name: "Wiatt Devey",
    emergency_relation: "father",
    emergency_phone_number: "3671191750",
    laptop_name: "Alienware Area-51",
    laptop_serial_no: "0XT0OH8TF0",
    employee_email: "wdeveyk@jugem.jp",
  },
  {
    full_name: "Huey Druery",
    employee_id: "E3448",
    date_of_birth: "68/72/3423",
    email: "fwitchardl@walmart.com",
    gender: "Male",
    marital_status: "single",
    blood_group: "A-",
    phone_number: "9045631946",
    address: "Suite 4",
    job_title: "Full stack Developer",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "Hyderabad",
    supervisor: "Elliot Badgers",
    emergency_contact_name: "Ferdy Witchard",
    emergency_relation: "mother",
    emergency_phone_number: "4006958128",
    laptop_name: "Lenovo ThinkPad",
    laptop_serial_no: "ABBW56GYIU",
    employee_email: "fwitchardl@arizona.edu",
  },
  {
    full_name: "Halsey Le Jean",
    employee_id: "E9122",
    date_of_birth: "07/97/8352",
    email: "klambrickm@webeden.co.uk",
    gender: "Male",
    marital_status: "single",
    blood_group: "B-",
    phone_number: "4740028413",
    address: "PO Box 39827",
    job_title: "Data_analyst",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "Ts",
    supervisor: "Bren Poulney",
    emergency_contact_name: "Keary Lambrick",
    emergency_relation: "son",
    emergency_phone_number: "5807181184",
    laptop_name: "Alienware Area-51",
    laptop_serial_no: "5S2GPHF2PC",
    employee_email: "klambrickm@umich.edu",
  },
  {
    full_name: "Kally Bothie",
    employee_id: "E1508",
    date_of_birth: "55/14/8660",
    email: "buphilln@nytimes.com",
    gender: "Female",
    marital_status: "single",
    blood_group: "B+",
    phone_number: "2961241032",
    address: "Suite 96",
    job_title: "AI",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "Ts",
    supervisor: "Chickie Mayger",
    emergency_contact_name: "Becka Uphill",
    emergency_relation: "father",
    emergency_phone_number: "7238075313",
    laptop_name: "Alienware Area-51",
    laptop_serial_no: "DB65VX4TLL",
    employee_email: "buphilln@usnews.com",
  },
  {
    full_name: "Vitia Skettles",
    employee_id: "E7728",
    date_of_birth: "18/17/9413",
    email: "liliffeo@pbs.org",
    gender: "Female",
    marital_status: "married",
    blood_group: "O-",
    phone_number: "5071381825",
    address: "PO Box 11992",
    job_title: "AI",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "Hyderabad",
    supervisor: "Ericka Esbrook",
    emergency_contact_name: "Leandra Iliffe",
    emergency_relation: "mother",
    emergency_phone_number: "4756124306",
    laptop_name: "Acer Swift",
    laptop_serial_no: "AI704UF9K6",
    employee_email: "liliffeo@eepurl.com",
  },
  {
    full_name: "Brad Thewless",
    employee_id: "E5295",
    date_of_birth: "26/63/5678",
    email: "eosmanp@businessweek.com",
    gender: "Male",
    marital_status: "single",
    blood_group: "O-",
    phone_number: "9527285933",
    address: "1st Floor",
    job_title: "Full stack Developer",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "Hyderabad",
    supervisor: "Ruggiero Lightowlers",
    emergency_contact_name: "Eduard Osman",
    emergency_relation: "mother",
    emergency_phone_number: "0058907796",
    laptop_name: "Dell XPS",
    laptop_serial_no: "EMV730K7BW",
    employee_email: "eosmanp@g.co",
  },
  {
    full_name: "Vincent Gladden",
    employee_id: "E8512",
    date_of_birth: "07/09/1808",
    email: "dgaylordq@apple.com",
    gender: "Male",
    marital_status: "single",
    blood_group: "B+",
    phone_number: "8964742025",
    address: "Apt 10",
    job_title: "AI",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "Ts",
    supervisor: "Mark Kellegher",
    emergency_contact_name: "Delainey Gaylord",
    emergency_relation: "brother",
    emergency_phone_number: "5464548980",
    laptop_name: "Lenovo ThinkPad",
    laptop_serial_no: "B0DHU880V4",
    employee_email: "dgaylordq@tuttocitta.it",
  },
  {
    full_name: "Nerti Gartenfeld",
    employee_id: "E9811",
    date_of_birth: "81/35/6688",
    email: "mtyer@moonfruit.com",
    gender: "Female",
    marital_status: "single",
    blood_group: "O+",
    phone_number: "3385549790",
    address: "PO Box 54992",
    job_title: "AI",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "Ts",
    supervisor: "Saidee Klimkin",
    emergency_contact_name: "Mufi Tye",
    emergency_relation: "mother",
    emergency_phone_number: "9412127041",
    laptop_name: "Asus ZenBook",
    laptop_serial_no: "6AEY331K15",
    employee_email: "mtyer@wikipedia.org",
  },
  {
    full_name: "Roze Danev",
    employee_id: "E3952",
    date_of_birth: "08/28/7017",
    email: "acosinss@tmall.com",
    gender: "Female",
    marital_status: "single",
    blood_group: "AB-",
    phone_number: "6301220189",
    address: "Apt 1054",
    job_title: "AI",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "India",
    supervisor: "Rici Delleschi",
    emergency_contact_name: "Alvera Cosins",
    emergency_relation: "brother",
    emergency_phone_number: "1060357828",
    laptop_name: "Apple MacBook Pro",
    laptop_serial_no: "7LZ3MR5261",
    employee_email: "acosinss@si.edu",
  },
  {
    full_name: "Wilone Baxstair",
    employee_id: "E8205",
    date_of_birth: "68/25/9598",
    email: "tbennt@chicagotribune.com",
    gender: "Female",
    marital_status: "single",
    blood_group: "O+",
    phone_number: "7334130510",
    address: "Apt 761",
    job_title: "Data_analyst",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "India",
    supervisor: "Lydia Allonby",
    emergency_contact_name: "Trescha Benn",
    emergency_relation: "brother",
    emergency_phone_number: "3337011957",
    laptop_name: "Dell XPS",
    laptop_serial_no: "07J81A2363",
    employee_email: "tbennt@cnn.com",
  },
  {
    full_name: "Bud Schimaschke",
    employee_id: "E1376",
    date_of_birth: "20/77/7619",
    email: "kraglesu@ask.com",
    gender: "Male",
    marital_status: "single",
    blood_group: "O+",
    phone_number: "5875877810",
    address: "Suite 63",
    job_title: "AI",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "Hyderabad",
    supervisor: "Gustavus Ivanishin",
    emergency_contact_name: "Kelwin Ragles",
    emergency_relation: "mother",
    emergency_phone_number: "8732595523",
    laptop_name: "Microsoft Surface",
    laptop_serial_no: "M3S010QIGL",
    employee_email: "kraglesu@rambler.ru",
  },
  {
    full_name: "Alysia Oxx",
    employee_id: "E1979",
    date_of_birth: "36/85/1218",
    email: "cdownagev@seesaa.net",
    gender: "Female",
    marital_status: "married",
    blood_group: "AB+",
    phone_number: "3782052526",
    address: "Suite 26",
    job_title: "Testing",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "Ts",
    supervisor: "Ofilia Strooband",
    emergency_contact_name: "Catlin Downage",
    emergency_relation: "father",
    emergency_phone_number: "9783167568",
    laptop_name: "Microsoft Surface",
    laptop_serial_no: "V7DLR02DEK",
    employee_email: "cdownagev@japanpost.jp",
  },
  {
    full_name: "Jecho Goldsbury",
    employee_id: "E9526",
    date_of_birth: "29/40/4373",
    email: "wsighardw@redcross.org",
    gender: "Male",
    marital_status: "married",
    blood_group: "B+",
    phone_number: "6996295322",
    address: "Suite 10",
    job_title: "Full stack Developer",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "India",
    supervisor: "Bernarr Gendrich",
    emergency_contact_name: "Wilfrid Sighard",
    emergency_relation: "father",
    emergency_phone_number: "3652682046",
    laptop_name: "Lenovo ThinkPad",
    laptop_serial_no: "9X0U9T673X",
    employee_email: "wsighardw@imgur.com",
  },
  {
    full_name: "Jessika Toffanelli",
    employee_id: "E8742",
    date_of_birth: "16/84/8175",
    email: "kcarniex@macromedia.com",
    gender: "Female",
    marital_status: "married",
    blood_group: "AB-",
    phone_number: "8140110576",
    address: "2nd Floor",
    job_title: "AI",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "India",
    supervisor: "Evie Buxcey",
    emergency_contact_name: "Kimberlee Carnie",
    emergency_relation: "mother",
    emergency_phone_number: "5837842207",
    laptop_name: "Asus ZenBook",
    laptop_serial_no: "1514V42EJZ",
    employee_email: "kcarniex@php.net",
  },
  {
    full_name: "Nikoletta Shankle",
    employee_id: "E3099",
    date_of_birth: "97/25/0004",
    email: "stoderiy@meetup.com",
    gender: "Female",
    marital_status: "married",
    blood_group: "A-",
    phone_number: "3245290421",
    address: "Suite 4",
    job_title: "Full stack Developer",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "Hyderabad",
    supervisor: "Odille Prosh",
    emergency_contact_name: "Sheelagh Toderi",
    emergency_relation: "father",
    emergency_phone_number: "5233828690",
    laptop_name: "Acer Swift",
    laptop_serial_no: "JQXB7L5MWV",
    employee_email: "stoderiy@geocities.jp",
  },
  {
    full_name: "Delly Boundley",
    employee_id: "E3058",
    date_of_birth: "52/93/0013",
    email: "dcaberasz@scientificamerican.com",
    gender: "Female",
    marital_status: "single",
    blood_group: "A+",
    phone_number: "2854762898",
    address: "17th Floor",
    job_title: "Testing",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "Ts",
    supervisor: "Zita Devorill",
    emergency_contact_name: "Dahlia Caberas",
    emergency_relation: "brother",
    emergency_phone_number: "5113373646",
    laptop_name: "HP Spectre",
    laptop_serial_no: "197YM0E614",
    employee_email: "dcaberasz@a8.net",
  },
  {
    full_name: "Dex Sirrell",
    employee_id: "E4496",
    date_of_birth: "99/79/9776",
    email: "rstrute10@seattletimes.com",
    gender: "Male",
    marital_status: "single",
    blood_group: "AB+",
    phone_number: "0794819241",
    address: "PO Box 22669",
    job_title: "Testing",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "Ts",
    supervisor: "Filmore Landa",
    emergency_contact_name: "Rollin Strute",
    emergency_relation: "brother",
    emergency_phone_number: "1185050509",
    laptop_name: "Acer Swift",
    laptop_serial_no: "75HU5BUT33",
    employee_email: "rstrute10@typepad.com",
  },
  {
    full_name: "Palm Tomasini",
    employee_id: "E4339",
    date_of_birth: "55/45/0066",
    email: "cizkovicz11@opensource.org",
    gender: "Male",
    marital_status: "married",
    blood_group: "O+",
    phone_number: "6348752976",
    address: "2nd Floor",
    job_title: "Data_analyst",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "Hyderabad",
    supervisor: "Mikkel Robroe",
    emergency_contact_name: "Cobb Izkovicz",
    emergency_relation: "father",
    emergency_phone_number: "8209083973",
    laptop_name: "Apple MacBook Pro",
    laptop_serial_no: "7300ORF62G",
    employee_email: "cizkovicz11@51.la",
  },
  {
    full_name: "Ina Krauss",
    employee_id: "E1334",
    date_of_birth: "71/16/3444",
    email: "khordle12@biglobe.ne.jp",
    gender: "Female",
    marital_status: "married",
    blood_group: "A-",
    phone_number: "9008421555",
    address: "Room 1282",
    job_title: "AI",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "Hyderabad",
    supervisor: "Reggie Osburn",
    emergency_contact_name: "Kalli Hordle",
    emergency_relation: "brother",
    emergency_phone_number: "9660730369",
    laptop_name: "Asus ZenBook",
    laptop_serial_no: "QHC2V9J7K0",
    employee_email: "khordle12@smugmug.com",
  },
  {
    full_name: "Rodolfo Swinnerton",
    employee_id: "E3943",
    date_of_birth: "73/64/4497",
    email: "pflips13@github.com",
    gender: "Male",
    marital_status: "single",
    blood_group: "AB+",
    phone_number: "1116133762",
    address: "Suite 40",
    job_title: "Full stack Developer",
    date_of_hire: "4/11/2023",
    department: "IT",
    work_location: "India",
    supervisor: "Olenolin Humbatch",
    emergency_contact_name: "Phillipp Flips",
    emergency_relation: "brother",
    emergency_phone_number: "4272932688",
    laptop_name: "Alienware Area-51",
    laptop_serial_no: "RCF5711141",
    employee_email: "pflips13@ow.ly",
  },
];
export default Data;
